- name: Test web content
  hosts: localhost
  become: true
  
  tasks:
    - name: Retrieve web content and write to error log on failure
      block:
        - name: Retrieve web content
          ansible.builtin.uri:
            url: "http://vagrant1"
            return_content: yes
          register: content
      rescue:
        - name: Write to error file
          ansible.builtin.copy:
            dest: ./error.log
            content: "{{ content | default('No content retrieved') }}"
            mode: '0644'
